# create your drupal and postgres config here, based off the last assignment
version: '2'
services:
  drupal:
    image: drupal:8
    container_name: drupal
    ports:
      - "80:80"
    volumes:
      - drupal:/opt/drupal
  postgres:
    image: postgres:12.1
    container_name: postgres
    environment:
      - POSTGRES_DB=drupal
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  drupal:
  postgres:
