# create your drupal and postgres config here, based off the last assignment
version: '2'
services:
  drupal:
    build:
        context: .
        dockerfile: Dockerfile
    image: custom-drupal
    container_name: drupal
    ports:
      - "80:80"
    volumes:
      - drupal:/opt/drupal
  postgres:
    image: postgres:12.1
    container_name: postgres
    environment:
      - POSTGRES_DB=drupal
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - drupal-data:/var/lib/postgresql/data
volumes:
  drupal:
  drupal-data:
